# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/runs/debug_${debug}/${name}_${data.name}_${n_demos}_${demo_selection}_${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/multiruns/${experiment}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}_${name}_${data.name}_${n_demos}_${demo_selection}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${name}.log
