# @package _global_

defaults:
  - _self_
  - data: DDR
  - hydra: concepts
  - paths: default

# pretty print config at the start of the run using Rich library
print_config: True

seed: 42

# setting debug=True limits the evaluation loop to process only 5 examples
debug: False

# --- Compute Configuration --- #
max_memory: null # {0: "8GiB", "cpu": "24GiB"}
max_memory_mistral: null # {0: "7GiB", "cpu": "24GiB"}
num_workers: 8

# ----- Model hyperparameters ----- #
max_new_tokens: 20
mistral_max_new_tokens: 100

# --- Experiment Configuration --- #
name: open-flamingo
bs: 16
n_demos: 0 # number of class examples in the prompt
demo_selection: null # choose between [rices, rices_per_class_global, rices_per_class_max, rices_per_class_mean, mmices, random, random_per_class]
feature_extractor: null # for RICES and MMICES
mmices_text_features: null # choose between [descriptions, concepts]
mmices_K: 100
precomputed_file: null # specify this file to avoid runing the LVLM again, i.e. processes the concept answers
filter: 1.0 # percentage of data for each class to keep
